//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M64MM2.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("M64MM2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Animation data not loaded!.
        /// </summary>
        internal static string animDataNotLoaded {
            get {
                return ResourceManager.GetString("animDataNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Camera data not loaded!.
        /// </summary>
        internal static string cameraDataNotLoaded {
            get {
                return ResourceManager.GetString("cameraDataNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Camera State: Default.
        /// </summary>
        internal static string cameraStateDefault {
            get {
                return ResourceManager.GetString("cameraStateDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Camera State: Frozen.
        /// </summary>
        internal static string cameraStateFrozen {
            get {
                return ResourceManager.GetString("cameraStateFrozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Camera State: Soft-Frozen.
        /// </summary>
        internal static string cameraStateSoftFrozen {
            get {
                return ResourceManager.GetString("cameraStateSoftFrozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CC_Mario_big {
            get {
                object obj = ResourceManager.GetObject("CC_Mario_big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comet ROMs need extra checks before being able to use color codes.
        ///Wait for a later update of both M64MM and CometROM!.
        /// </summary>
        internal static string colorCodeCometRom {
            get {
                return ResourceManager.GetString("colorCodeCometRom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ...This ROM has no model data.
        ///The color codes and shading only apply to vanilla models and mods that support it..
        /// </summary>
        internal static string colorCodeEmptyRom {
            get {
                return ResourceManager.GetString("colorCodeEmptyRom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Here&apos;s your generated color code:.
        /// </summary>
        internal static string colorCodeExportMsg {
            get {
                return ResourceManager.GetString("colorCodeExportMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please paste your color code below, then click OK..
        /// </summary>
        internal static string colorCodeImportMsg {
            get {
                return ResourceManager.GetString("colorCodeImportMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This ROM has a different model data compared to Mario&apos;s usual model data and is not a compatible CometROM. The Color Code Studio and Shading Editor have been disabled; they might not work correctly in this ROM..
        /// </summary>
        internal static string colorCodeModdedRom {
            get {
                return ResourceManager.GetString("colorCodeModdedRom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://comet.glitchypsi.xyz.
        /// </summary>
        internal static string discordInvite {
            get {
                return ResourceManager.GetString("discordInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have entered an invalid animation name into {0}. Please make sure to choose a valid option from the list..
        /// </summary>
        internal static string invalidAnimSelected {
            get {
                return ResourceManager.GetString("invalidAnimSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid color code: line {0} is too {1}..
        /// </summary>
        internal static string invalidColorCodeMsg1 {
            get {
                return ResourceManager.GetString("invalidColorCodeMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid color code: line {0} is trying to edit memory address {1}, which is not where Mario&apos;s color data is located. Make sure you&apos;re not using a PAL region color code!.
        /// </summary>
        internal static string invalidColorCodeMsg2 {
            get {
                return ResourceManager.GetString("invalidColorCodeMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a long.
        /// </summary>
        internal static string invalidColorCodeMsgLong {
            get {
                return ResourceManager.GetString("invalidColorCodeMsgLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a short.
        /// </summary>
        internal static string invalidColorCodeMsgShort {
            get {
                return ResourceManager.GetString("invalidColorCodeMsgShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid Color Code.
        /// </summary>
        internal static string invalidColorCodeMsgTitle {
            get {
                return ResourceManager.GetString("invalidColorCodeMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap m3_splash {
            get {
                object obj = ResourceManager.GetObject("m3_splash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        internal static System.Drawing.Icon M64MM2 {
            get {
                object obj = ResourceManager.GetObject("M64MM2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap M64MM2_Icon {
            get {
                object obj = ResourceManager.GetObject("M64MM2_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        internal static System.Drawing.Icon M64MM2_New {
            get {
                object obj = ResourceManager.GetObject("M64MM2_New", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap M64MM2_New_Icon {
            get {
                object obj = ResourceManager.GetObject("M64MM2_New_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap M64MM2_New_Icon_2 {
            get {
                object obj = ResourceManager.GetObject("M64MM2_New_Icon_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap m64mm3_banner {
            get {
                object obj = ResourceManager.GetObject("m64mm3_banner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a In banner: .
        /// </summary>
        internal static string picturedInBannerMsg {
            get {
                return ResourceManager.GetString("picturedInBannerMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Onewingdangl, Captainswag101, GlitchyPSI.
        /// </summary>
        internal static string picturedInBannerPeople {
            get {
                return ResourceManager.GetString("picturedInBannerPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -alpha1.h2.
        /// </summary>
        internal static string prereleaseString {
            get {
                return ResourceManager.GetString("prereleaseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M64MM Classic.
        /// </summary>
        internal static string programName {
            get {
                return ResourceManager.GetString("programName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status: Project64 is not open..
        /// </summary>
        internal static string programStatus1 {
            get {
                return ResourceManager.GetString("programStatus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status: Base address not found..
        /// </summary>
        internal static string programStatus2 {
            get {
                return ResourceManager.GetString("programStatus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status: Base address found at .
        /// </summary>
        internal static string programStatus3 {
            get {
                return ResourceManager.GetString("programStatus3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status: Waiting for level. Base addr. found at:.
        /// </summary>
        internal static string programStatusAwaitingLevel {
            get {
                return ResourceManager.GetString("programStatusAwaitingLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set these colors as default?.
        /// </summary>
        internal static string setDefaultColorsMsg {
            get {
                return ResourceManager.GetString("setDefaultColorsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set defaults?.
        /// </summary>
        internal static string setDefaultColorsMsgTitle {
            get {
                return ResourceManager.GetString("setDefaultColorsMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap version3 {
            get {
                object obj = ResourceManager.GetObject("version3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap version3_big {
            get {
                object obj = ResourceManager.GetObject("version3_big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
