//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M64MM2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("M64MM2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addons.
        /// </summary>
        internal static string addonsButton {
            get {
                return ResourceManager.GetString("addonsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addon warnings.
        /// </summary>
        internal static string addonWarnings {
            get {
                return ResourceManager.GetString("addonWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation data not loaded!.
        /// </summary>
        internal static string animDataNotLoaded {
            get {
                return ResourceManager.GetString("animDataNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera data not loaded!.
        /// </summary>
        internal static string cameraDataNotLoaded {
            get {
                return ResourceManager.GetString("cameraDataNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera State: Default.
        /// </summary>
        internal static string cameraStateDefault {
            get {
                return ResourceManager.GetString("cameraStateDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera State: Frozen.
        /// </summary>
        internal static string cameraStateFrozen {
            get {
                return ResourceManager.GetString("cameraStateFrozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera State: Soft-Frozen.
        /// </summary>
        internal static string cameraStateSoftFrozen {
            get {
                return ResourceManager.GetString("cameraStateSoftFrozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frozen: .
        /// </summary>
        internal static string cameraToggleFrozen {
            get {
                return ResourceManager.GetString("cameraToggleFrozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft-frozen: .
        /// </summary>
        internal static string cameraToggleSoftFrozen {
            get {
                return ResourceManager.GetString("cameraToggleSoftFrozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CC_Mario_big {
            get {
                object obj = ResourceManager.GetObject("CC_Mario_big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...This ROM has no model data.
        ///The color codes and shading only apply to vanilla models and mods that support it..
        /// </summary>
        internal static string colorCodeEmptyRom {
            get {
                return ResourceManager.GetString("colorCodeEmptyRom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read color code from file.\n{0}.
        /// </summary>
        internal static string colorCodeErrorFileReading {
            get {
                return ResourceManager.GetString("colorCodeErrorFileReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not write color code to file.\n{0}.
        /// </summary>
        internal static string colorCodeErrorWriting {
            get {
                return ResourceManager.GetString("colorCodeErrorWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here&apos;s your generated color code:.
        /// </summary>
        internal static string colorCodeExportMsg {
            get {
                return ResourceManager.GetString("colorCodeExportMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From file....
        /// </summary>
        internal static string colorCodeFromFile {
            get {
                return ResourceManager.GetString("colorCodeFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please paste your color code below, then click OK..
        /// </summary>
        internal static string colorCodeImportMsg {
            get {
                return ResourceManager.GetString("colorCodeImportMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ROM has a different model data compared to Mario&apos;s usual model data. If you&apos;re using a X3S ROM, change the Color Parts Override to X3S to use it..
        /// </summary>
        internal static string colorCodeModdedRom {
            get {
                return ResourceManager.GetString("colorCodeModdedRom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a ROM with a header that looks like a SPARK color codeable mod. Currently, the Appearance Settings does not support SPARK, so you might want to get the CometSPARK Editor Addon at https://comet.glitchypsi.xyz.
        /// </summary>
        internal static string colorCodeSPARKRom {
            get {
                return ResourceManager.GetString("colorCodeSPARKRom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To file....
        /// </summary>
        internal static string colorCodeToFile {
            get {
                return ResourceManager.GetString("colorCodeToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://comet.glitchypsi.xyz.
        /// </summary>
        internal static string discordInvite {
            get {
                return ResourceManager.GetString("discordInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected emulator (or only available opened emulators) cannot be accessed by M64MM.
        ///This often happens if the emulator started as Administrator.
        ///There is no reason to start the emulator as an administrator. To use M64MM, please start the emulator without administrator privileges..
        /// </summary>
        internal static string inaccessibleEmuMsg {
            get {
                return ResourceManager.GetString("inaccessibleEmuMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have opted to use the {0} parts, but this ROM is {1}.
        ///Stability not guaranteed..
        /// </summary>
        internal static string incompatibleModelMsg {
            get {
                return ResourceManager.GetString("incompatibleModelMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered an invalid animation name into {0}. Please make sure to choose a valid option from the list..
        /// </summary>
        internal static string invalidAnimSelected {
            get {
                return ResourceManager.GetString("invalidAnimSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid color code: line {0} is too {1}..
        /// </summary>
        internal static string invalidColorCodeMsg1 {
            get {
                return ResourceManager.GetString("invalidColorCodeMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid color code: line {0} is trying to edit memory address {1}, which is not where Mario&apos;s color data is located. Make sure you&apos;re not using a PAL region color code!.
        /// </summary>
        internal static string invalidColorCodeMsg2 {
            get {
                return ResourceManager.GetString("invalidColorCodeMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to long.
        /// </summary>
        internal static string invalidColorCodeMsgLong {
            get {
                return ResourceManager.GetString("invalidColorCodeMsgLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to short.
        /// </summary>
        internal static string invalidColorCodeMsgShort {
            get {
                return ResourceManager.GetString("invalidColorCodeMsgShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Color Code.
        /// </summary>
        internal static string invalidColorCodeMsgTitle {
            get {
                return ResourceManager.GetString("invalidColorCodeMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap m3_splash {
            get {
                object obj = ResourceManager.GetObject("m3_splash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap m3_splash_dev {
            get {
                object obj = ResourceManager.GetObject("m3_splash_dev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap m64mm_hero {
            get {
                object obj = ResourceManager.GetObject("m64mm_hero", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap m64mm_hero_devprev {
            get {
                object obj = ResourceManager.GetObject("m64mm_hero_devprev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon M64MM2 {
            get {
                object obj = ResourceManager.GetObject("M64MM2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap M64MM2_Icon {
            get {
                object obj = ResourceManager.GetObject("M64MM2_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon M64MM2_New {
            get {
                object obj = ResourceManager.GetObject("M64MM2_New", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap M64MM2_New_Icon {
            get {
                object obj = ResourceManager.GetObject("M64MM2_New_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap M64MM2_New_Icon_2 {
            get {
                object obj = ResourceManager.GetObject("M64MM2_New_Icon_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap m64mm3_banner {
            get {
                object obj = ResourceManager.GetObject("m64mm3_banner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option is in early preview. Will most likely explode and will most likely kill the game if done in a level other than Castle Grounds. You&apos;ve been warned..
        /// </summary>
        internal static string peachGrassMsg {
            get {
                return ResourceManager.GetString("peachGrassMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In banner: .
        /// </summary>
        internal static string picturedInBannerMsg {
            get {
                return ResourceManager.GetString("picturedInBannerMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onewingdangl, Captainswag101, GlitchyPSI.
        /// </summary>
        internal static string picturedInBannerPeople {
            get {
                return ResourceManager.GetString("picturedInBannerPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You started the game in a level that would cause problems with Powercam, so you can&apos;t enable it here.
        ///Enter a level that doesn&apos;t zoom out when the game is paused and enable Powercam again..
        /// </summary>
        internal static string powercamIngameDirtyMsg {
            get {
                return ResourceManager.GetString("powercamIngameDirtyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a time and a place for everything, but not here!.
        /// </summary>
        internal static string powercamIngameDirtyTitle {
            get {
                return ResourceManager.GetString("powercamIngameDirtyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You started the game in a level that would mess with your camera if Powercam is first enabled in it, so we&apos;ve disabled it for you.
        ///Enter a level that doesn&apos;t zoom out when the game is paused and enable Powercam again..
        /// </summary>
        internal static string powercamPregameDirtyMsg {
            get {
                return ResourceManager.GetString("powercamPregameDirtyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait, this is important..
        /// </summary>
        internal static string powercamPregameDirtyTitle {
            get {
                return ResourceManager.GetString("powercamPregameDirtyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -alpha8.b1.
        /// </summary>
        internal static string prereleaseString {
            get {
                return ResourceManager.GetString("prereleaseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M64MM Classic.
        /// </summary>
        internal static string programName {
            get {
                return ResourceManager.GetString("programName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Project64/Mupen not open..
        /// </summary>
        internal static string programStatus1 {
            get {
                return ResourceManager.GetString("programStatus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Base address not found..
        /// </summary>
        internal static string programStatus2 {
            get {
                return ResourceManager.GetString("programStatus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Base address found at .
        /// </summary>
        internal static string programStatus3 {
            get {
                return ResourceManager.GetString("programStatus3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Waiting for level. Base addr. found at:.
        /// </summary>
        internal static string programStatusAwaitingLevel {
            get {
                return ResourceManager.GetString("programStatusAwaitingLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Couldn&apos;t open Project64/Mupen.
        /// </summary>
        internal static string programStatusInaccessible {
            get {
                return ResourceManager.GetString("programStatusInaccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap randomSlot {
            get {
                object obj = ResourceManager.GetObject("randomSlot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set these colors as default?.
        /// </summary>
        internal static string setDefaultColorsMsg {
            get {
                return ResourceManager.GetString("setDefaultColorsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set defaults?.
        /// </summary>
        internal static string setDefaultColorsMsgTitle {
            get {
                return ResourceManager.GetString("setDefaultColorsMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap superg_m64mmsplash {
            get {
                object obj = ResourceManager.GetObject("superg_m64mmsplash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string taskManDescription {
            get {
                return ResourceManager.GetString("taskManDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Please select an item.&gt;.
        /// </summary>
        internal static string taskManSelect {
            get {
                return ResourceManager.GetString("taskManSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current:.
        /// </summary>
        internal static string updateCurrentVersion {
            get {
                return ResourceManager.GetString("updateCurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest: .
        /// </summary>
        internal static string updateLatestVersion {
            get {
                return ResourceManager.GetString("updateLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened. Could not reach the GitHub page for updates. Check your network connection..
        /// </summary>
        internal static string updateNetworkError {
            get {
                return ResourceManager.GetString("updateNetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Update available!).
        /// </summary>
        internal static string updateUpdateNow {
            get {
                return ResourceManager.GetString("updateUpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (You&apos;re up to date!).
        /// </summary>
        internal static string updateUpToDate {
            get {
                return ResourceManager.GetString("updateUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap version3 {
            get {
                object obj = ResourceManager.GetObject("version3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap version3_2big {
            get {
                object obj = ResourceManager.GetObject("version3_2big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap version3_big {
            get {
                object obj = ResourceManager.GetObject("version3_big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon version32 {
            get {
                object obj = ResourceManager.GetObject("version32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap webb_m64mmsplash {
            get {
                object obj = ResourceManager.GetObject("webb_m64mmsplash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The X3S Tint is only available for the X3 + Shading mods distributed by Project Comet or other affiliated people.
        ///Changing the tint in a non-X3S ROM may cause distortions, an unexpected color being changed, or nothing..
        /// </summary>
        internal static string x3sMsg {
            get {
                return ResourceManager.GetString("x3sMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
