//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M64MM2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("M64MM2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation data not loaded!.
        /// </summary>
        internal static string animDataNotLoaded {
            get {
                return ResourceManager.GetString("animDataNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera data not loaded!.
        /// </summary>
        internal static string cameraDataNotLoaded {
            get {
                return ResourceManager.GetString("cameraDataNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera State: Default.
        /// </summary>
        internal static string cameraStateDefault {
            get {
                return ResourceManager.GetString("cameraStateDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera State: Frozen.
        /// </summary>
        internal static string cameraStateFrozen {
            get {
                return ResourceManager.GetString("cameraStateFrozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera State: Soft-Frozen.
        /// </summary>
        internal static string cameraStateSoftFrozen {
            get {
                return ResourceManager.GetString("cameraStateSoftFrozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CC_Mario_big {
            get {
                object obj = ResourceManager.GetObject("CC_Mario_big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here&apos;s your generated color code:.
        /// </summary>
        internal static string colorCodeExportMsg {
            get {
                return ResourceManager.GetString("colorCodeExportMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please paste your color code below, then click OK..
        /// </summary>
        internal static string colorCodeImportMsg {
            get {
                return ResourceManager.GetString("colorCodeImportMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid color code: line {0} is too {1}..
        /// </summary>
        internal static string invalidColorCodeMsg1 {
            get {
                return ResourceManager.GetString("invalidColorCodeMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid color code: line {0} is trying to edit memory address {1}, which is not where Mario&apos;s color data is located. Make sure you&apos;re not using a PAL region color code!.
        /// </summary>
        internal static string invalidColorCodeMsg2 {
            get {
                return ResourceManager.GetString("invalidColorCodeMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to long.
        /// </summary>
        internal static string invalidColorCodeMsgLong {
            get {
                return ResourceManager.GetString("invalidColorCodeMsgLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to short.
        /// </summary>
        internal static string invalidColorCodeMsgShort {
            get {
                return ResourceManager.GetString("invalidColorCodeMsgShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Color Code.
        /// </summary>
        internal static string invalidColorCodeMsgTitle {
            get {
                return ResourceManager.GetString("invalidColorCodeMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon M64MM2 {
            get {
                object obj = ResourceManager.GetObject("M64MM2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap M64MM2_Icon {
            get {
                object obj = ResourceManager.GetObject("M64MM2_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Project64 is not open..
        /// </summary>
        internal static string programStatus1 {
            get {
                return ResourceManager.GetString("programStatus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Base address not found..
        /// </summary>
        internal static string programStatus2 {
            get {
                return ResourceManager.GetString("programStatus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Base address found at .
        /// </summary>
        internal static string programStatus3 {
            get {
                return ResourceManager.GetString("programStatus3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set these colors as default?.
        /// </summary>
        internal static string setDefaultColorsMsg {
            get {
                return ResourceManager.GetString("setDefaultColorsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set defaults?.
        /// </summary>
        internal static string setDefaultColorsMsgTitle {
            get {
                return ResourceManager.GetString("setDefaultColorsMsgTitle", resourceCulture);
            }
        }
    }
}
