'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("M64MM2.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Created by James &quot;CaptainSwag101&quot; Pelster.
        '''</summary>
        Friend ReadOnly Property AboutCreatorDesc() As String
            Get
                Return ResourceManager.GetString("AboutCreatorDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This program is dedicated to the Super Mario 64 Bloopers/Machinima community, thanks for all the effort you&apos;ve put into your work, and I hope this tool will help you create awesome videos for years to come!.
        '''</summary>
        Friend ReadOnly Property AboutText1() As String
            Get
                Return ResourceManager.GetString("AboutText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Special thanks to Matthew &quot;MATTHEWGU4&quot; Guerra for helping me make this project a reality and for spreading the word, and to GlitchyPSIX for his discovery of the &quot;Soft-Freeze&quot; feature..
        '''</summary>
        Friend ReadOnly Property AboutText2() As String
            Get
                Return ResourceManager.GetString("AboutText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Found any bugs, need help, or want to suggest a feature? Email me at:.
        '''</summary>
        Friend ReadOnly Property AboutText3() As String
            Get
                Return ResourceManager.GetString("AboutText3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The base address is: .
        '''</summary>
        Friend ReadOnly Property BaseAddressIs() As String
            Get
                Return ResourceManager.GetString("BaseAddressIs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Base address not found!.
        '''</summary>
        Friend ReadOnly Property BaseAddressNotFound() As String
            Get
                Return ResourceManager.GetString("BaseAddressNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You are attempting to write to the first four bytes of Super Mario 64&apos;s memory, which contains the value this program uses to find the game&apos;s base address. If you click &quot;&quot;Yes&quot;&quot;, you will need to reset the emulator before this program will be able to find Super Mario 64 again. Are you sure you want to do this?.
        '''</summary>
        Friend ReadOnly Property BaseAddressOverwriteWarning() As String
            Get
                Return ResourceManager.GetString("BaseAddressOverwriteWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Camera position locked. Click the button below to lock camera rotation..
        '''</summary>
        Friend ReadOnly Property CameraLockDesc() As String
            Get
                Return ResourceManager.GetString("CameraLockDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Camera rotation unlocked. Click the button below to lock camera rotation..
        '''</summary>
        Friend ReadOnly Property CameraUnlockDesc() As String
            Get
                Return ResourceManager.GetString("CameraUnlockDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IMPORTANT: Make sure to uncheck any color codes currently enabled in Project64. Otherwise, they will prevent this program from modifying Mario&apos;s colors..
        '''</summary>
        Friend ReadOnly Property CCWarning() As String
            Get
                Return ResourceManager.GetString("CCWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change Camera Type.
        '''</summary>
        Friend ReadOnly Property ChangeCameraType() As String
            Get
                Return ResourceManager.GetString("ChangeCameraType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Freeze Camera.
        '''</summary>
        Friend ReadOnly Property FreezeCamera() As String
            Get
                Return ResourceManager.GetString("FreezeCamera", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Go to new area.
        '''</summary>
        Friend ReadOnly Property GotoNewArea() As String
            Get
                Return ResourceManager.GetString("GotoNewArea", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The value you have entered is not a valid Hexadecimal address..
        '''</summary>
        Friend ReadOnly Property InvalidHexAddress() As String
            Get
                Return ResourceManager.GetString("InvalidHexAddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The number you have entered is not a valid Hexadecimal value..
        '''</summary>
        Friend ReadOnly Property InvalidHexValue() As String
            Get
                Return ResourceManager.GetString("InvalidHexValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property M64MM2_CC_Mario_big() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("M64MM2_CC_Mario_big", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property M64MM2_Icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("M64MM2_Icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This window is for testing reading from/writing to SM64&apos;s memory (RAM). You should only use this if you know what you&apos;re doing. The developers accept no responsibility for lost save data, program crashes, or system crashes..
        '''</summary>
        Friend ReadOnly Property MemDebugWarning() As String
            Get
                Return ResourceManager.GetString("MemDebugWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scanning for base address....
        '''</summary>
        Friend ReadOnly Property SearchingForBaseAddress() As String
            Get
                Return ResourceManager.GetString("SearchingForBaseAddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unfreeze Camera.
        '''</summary>
        Friend ReadOnly Property UnfreezeCamera() As String
            Get
                Return ResourceManager.GetString("UnfreezeCamera", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
