'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("M64MM2.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Build Date: .
        '''</summary>
        Public ReadOnly Property AboutBuildDate() As String
            Get
                Return ResourceManager.GetString("AboutBuildDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Created by James &quot;CaptainSwag101&quot; Pelster &amp; GlitchyPSIX.
        '''</summary>
        Public ReadOnly Property AboutCreatorDesc() As String
            Get
                Return ResourceManager.GetString("AboutCreatorDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Help.
        '''</summary>
        Public ReadOnly Property AboutMenu() As String
            Get
                Return ResourceManager.GetString("AboutMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to About Mario 64 Movie Maker 2.0.5.1....
        '''</summary>
        Public ReadOnly Property AboutStrip() As String
            Get
                Return ResourceManager.GetString("AboutStrip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This program is dedicated to the Super Mario 64 Bloopers/Machinima community, thanks for all the effort you&apos;ve put into your work, and I hope this tool will help you create awesome videos for years to come!.
        '''</summary>
        Public ReadOnly Property AboutText1() As String
            Get
                Return ResourceManager.GetString("AboutText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Special thanks to Matthew &quot;MATTHEWGU4&quot; Guerra for helping me make this project a reality and for spreading the word, and to GlitchyPSIX for his attributions to the program..
        '''</summary>
        Public ReadOnly Property AboutText2() As String
            Get
                Return ResourceManager.GetString("AboutText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Found any bugs, need help, or want to suggest a feature? Email me at:.
        '''</summary>
        Public ReadOnly Property AboutText3() As String
            Get
                Return ResourceManager.GetString("AboutText3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Animation data not loaded!.
        '''</summary>
        Public ReadOnly Property AnimationDataNotLoaded() As String
            Get
                Return ResourceManager.GetString("AnimationDataNotLoaded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error reading animation data file:.
        '''</summary>
        Public ReadOnly Property AnimationDataReadError() As String
            Get
                Return ResourceManager.GetString("AnimationDataReadError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Animation Swap Control.
        '''</summary>
        Public ReadOnly Property AnimationGroupName() As String
            Get
                Return ResourceManager.GetString("AnimationGroupName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Overwrite this animation....
        '''</summary>
        Public ReadOnly Property AnimationO1() As String
            Get
                Return ResourceManager.GetString("AnimationO1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ...with this one!.
        '''</summary>
        Public ReadOnly Property AnimationO2() As String
            Get
                Return ResourceManager.GetString("AnimationO2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Back.
        '''</summary>
        Public ReadOnly Property Back() As String
            Get
                Return ResourceManager.GetString("Back", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The base address is: .
        '''</summary>
        Public ReadOnly Property BaseAddressIs() As String
            Get
                Return ResourceManager.GetString("BaseAddressIs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Base address not found!.
        '''</summary>
        Public ReadOnly Property BaseAddressNotFound() As String
            Get
                Return ResourceManager.GetString("BaseAddressNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You are attempting to write to the first four bytes of Super Mario 64&apos;s memory, which contains the value this program uses to find the game&apos;s base address. If you click &quot;&quot;Yes&quot;&quot;, you will need to reset the emulator before this program will be able to find Super Mario 64 again. Are you sure you want to do this?.
        '''</summary>
        Public ReadOnly Property BaseAddressOverwriteWarning() As String
            Get
                Return ResourceManager.GetString("BaseAddressOverwriteWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Normal Camera Controls.
        '''</summary>
        Public ReadOnly Property CamControlName() As String
            Get
                Return ResourceManager.GetString("CamControlName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Camera position locked. Click the button below or use CTRL+SHIFT+P to lock the camera rotation..
        '''</summary>
        Public ReadOnly Property CameraLockDesc() As String
            Get
                Return ResourceManager.GetString("CameraLockDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Camera rotation unlocked. Click the button below or use CTRL+SHIFT+P to lock camera rotation..
        '''</summary>
        Public ReadOnly Property CameraUnlockDesc() As String
            Get
                Return ResourceManager.GetString("CameraUnlockDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CC Mode.
        '''</summary>
        Public ReadOnly Property CCS_ColorMode() As String
            Get
                Return ResourceManager.GetString("CCS_ColorMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Restore Lighting.
        '''</summary>
        Public ReadOnly Property CCS_RestoreSh() As String
            Get
                Return ResourceManager.GetString("CCS_RestoreSh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Light point X.
        '''</summary>
        Public ReadOnly Property CCS_ShadeX() As String
            Get
                Return ResourceManager.GetString("CCS_ShadeX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Light point Y.
        '''</summary>
        Public ReadOnly Property CCS_ShadeY() As String
            Get
                Return ResourceManager.GetString("CCS_ShadeY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Light point Z.
        '''</summary>
        Public ReadOnly Property CCS_ShadeZ() As String
            Get
                Return ResourceManager.GetString("CCS_ShadeZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lighting Mode.
        '''</summary>
        Public ReadOnly Property CCS_ShadingMode() As String
            Get
                Return ResourceManager.GetString("CCS_ShadingMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Want to set these colors as default?.
        '''</summary>
        Public ReadOnly Property CCSDefaultMB() As String
            Get
                Return ResourceManager.GetString("CCSDefaultMB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Restore Colors.
        '''</summary>
        Public ReadOnly Property CCSDefaults() As String
            Get
                Return ResourceManager.GetString("CCSDefaults", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set as default?.
        '''</summary>
        Public ReadOnly Property CCSDMBTitle() As String
            Get
                Return ResourceManager.GetString("CCSDMBTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close.
        '''</summary>
        Public ReadOnly Property CCSEXbtn() As String
            Get
                Return ResourceManager.GetString("CCSEXbtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Public ReadOnly Property CCSEXCancel() As String
            Get
                Return ResourceManager.GetString("CCSEXCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Here&apos;s that color code you asked for!.
        '''</summary>
        Public ReadOnly Property CCSEXLabel() As String
            Get
                Return ResourceManager.GetString("CCSEXLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export color code....
        '''</summary>
        Public ReadOnly Property CCSExport() As String
            Get
                Return ResourceManager.GetString("CCSExport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Color Code Studio.
        '''</summary>
        Public ReadOnly Property CCSFormTitle() As String
            Get
                Return ResourceManager.GetString("CCSFormTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gloves.
        '''</summary>
        Public ReadOnly Property CCSGloves() As String
            Get
                Return ResourceManager.GetString("CCSGloves", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hair.
        '''</summary>
        Public ReadOnly Property CCSHair() As String
            Get
                Return ResourceManager.GetString("CCSHair", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hat/Shirt.
        '''</summary>
        Public ReadOnly Property CCSHat() As String
            Get
                Return ResourceManager.GetString("CCSHat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Paste your color code into the textbox below, then click &quot;OK&quot;..
        '''</summary>
        Public ReadOnly Property CCSIMLabel() As String
            Get
                Return ResourceManager.GetString("CCSIMLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Import color code....
        '''</summary>
        Public ReadOnly Property CCSImport() As String
            Get
                Return ResourceManager.GetString("CCSImport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error occurred while trying to import the color code. Make sure you entered a valid code!.
        '''</summary>
        Public ReadOnly Property CCSImportError() As String
            Get
                Return ResourceManager.GetString("CCSImportError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Load from game.
        '''</summary>
        Public ReadOnly Property CCSLoad() As String
            Get
                Return ResourceManager.GetString("CCSLoad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Overalls.
        '''</summary>
        Public ReadOnly Property CCSOveralls() As String
            Get
                Return ResourceManager.GetString("CCSOveralls", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shoes.
        '''</summary>
        Public ReadOnly Property CCSShoes() As String
            Get
                Return ResourceManager.GetString("CCSShoes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Skin.
        '''</summary>
        Public ReadOnly Property CCSSkin() As String
            Get
                Return ResourceManager.GetString("CCSSkin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IMPORTANT: Make sure to uncheck any color codes currently enabled in Project64. Otherwise, they will prevent this program from modifying Mario&apos;s colors..
        '''</summary>
        Public ReadOnly Property CCWarning() As String
            Get
                Return ResourceManager.GetString("CCWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change Camera Type.
        '''</summary>
        Public ReadOnly Property ChangeCameraType() As String
            Get
                Return ResourceManager.GetString("ChangeCameraType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Force Camera to be movable with C-Buttons.
        '''</summary>
        Public ReadOnly Property ForceCameraC() As String
            Get
                Return ResourceManager.GetString("ForceCameraC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click this whenever you are in an area that does not allow
        '''the camera to be rotated with the C-buttons (such as the
        '''inside of the castle) and the camera will be temporarily allowed
        '''to be manually rotated in the usual manner. However, this
        '''does not always work in all areas of the castle, as sometimes
        '''camera behaviors are hardcoded into specific parts of levels..
        '''</summary>
        Public ReadOnly Property ForceCameraCTooltip() As String
            Get
                Return ResourceManager.GetString("ForceCameraCTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Freeze Camera.
        '''</summary>
        Public ReadOnly Property FreezeCamera() As String
            Get
                Return ResourceManager.GetString("FreezeCamera", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Front.
        '''</summary>
        Public ReadOnly Property Front() As String
            Get
                Return ResourceManager.GetString("Front", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Go to new area.
        '''</summary>
        Public ReadOnly Property GotoNewArea() As String
            Get
                Return ResourceManager.GetString("GotoNewArea", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Heal Mario (nonfunctional).
        '''</summary>
        Public ReadOnly Property Heal_Extra() As String
            Get
                Return ResourceManager.GetString("Heal_Extra", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Higher.
        '''</summary>
        Public ReadOnly Property Higher() As String
            Get
                Return ResourceManager.GetString("Higher", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hover Control.
        '''</summary>
        Public ReadOnly Property HoverControlName() As String
            Get
                Return ResourceManager.GetString("HoverControlName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 5 (Highest).
        '''</summary>
        Public ReadOnly Property HoverMax() As String
            Get
                Return ResourceManager.GetString("HoverMax", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0 (None).
        '''</summary>
        Public ReadOnly Property HoverMin() As String
            Get
                Return ResourceManager.GetString("HoverMin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reminder: Some animations won&apos;t be affected by this. Recommended value is 1..
        '''</summary>
        Public ReadOnly Property HoverToolTip() As String
            Get
                Return ResourceManager.GetString("HoverToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The value you have entered is not a valid Hexadecimal address..
        '''</summary>
        Public ReadOnly Property InvalidHexAddress() As String
            Get
                Return ResourceManager.GetString("InvalidHexAddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The number you have entered is not a valid Hexadecimal value..
        '''</summary>
        Public ReadOnly Property InvalidHexValue() As String
            Get
                Return ResourceManager.GetString("InvalidHexValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address:.
        '''</summary>
        Public ReadOnly Property IOAddr() As String
            Get
                Return ResourceManager.GetString("IOAddr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I know what I&apos;m doing..
        '''</summary>
        Public ReadOnly Property IOBadass() As String
            Get
                Return ResourceManager.GetString("IOBadass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Memory I/O Editor.
        '''</summary>
        Public ReadOnly Property IOFormTitle() As String
            Get
                Return ResourceManager.GetString("IOFormTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Memory Controls.
        '''</summary>
        Public ReadOnly Property IOGroupName() As String
            Get
                Return ResourceManager.GetString("IOGroupName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Read.
        '''</summary>
        Public ReadOnly Property IORead() As String
            Get
                Return ResourceManager.GetString("IORead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Value:.
        '''</summary>
        Public ReadOnly Property IOValue() As String
            Get
                Return ResourceManager.GetString("IOValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Write.
        '''</summary>
        Public ReadOnly Property IOWrite() As String
            Get
                Return ResourceManager.GetString("IOWrite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Left.
        '''</summary>
        Public ReadOnly Property Left() As String
            Get
                Return ResourceManager.GetString("Left", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Licensing Info....
        '''</summary>
        Public ReadOnly Property LicenseStrip() As String
            Get
                Return ResourceManager.GetString("LicenseStrip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lower.
        '''</summary>
        Public ReadOnly Property Lower() As String
            Get
                Return ResourceManager.GetString("Lower", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property M64MM2_CC_Mario_big() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("M64MM2_CC_Mario_big", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property M64MM2_Icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("M64MM2_Icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This window is for testing reading from/writing to SM64&apos;s memory (RAM). You should only use this if you know what you&apos;re doing. The developers accept no responsibility for lost save data, program crashes, or system crashes..
        '''</summary>
        Public ReadOnly Property MemDebugWarning() As String
            Get
                Return ResourceManager.GetString("MemDebugWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You cannot turn on the Precision Mode because Project64 isn&apos;t open..
        '''</summary>
        Public ReadOnly Property NoPJPrecisionError() As String
            Get
                Return ResourceManager.GetString("NoPJPrecisionError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Project64 isn&apos;t open!.
        '''</summary>
        Public ReadOnly Property PJNotOpen() As String
            Get
                Return ResourceManager.GetString("PJNotOpen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Precision Mode is off..
        '''</summary>
        Public ReadOnly Property PrecisionButtonDisabled() As String
            Get
                Return ResourceManager.GetString("PrecisionButtonDisabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lock Camera Rotation.
        '''</summary>
        Public ReadOnly Property PrecisionButtonLock() As String
            Get
                Return ResourceManager.GetString("PrecisionButtonLock", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unlock Camera Rotation.
        '''</summary>
        Public ReadOnly Property PrecisionButtonUnlock() As String
            Get
                Return ResourceManager.GetString("PrecisionButtonUnlock", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Precision Camera Control.
        '''</summary>
        Public ReadOnly Property PrecisionGroupName() As String
            Get
                Return ResourceManager.GetString("PrecisionGroupName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Precision Camera Control.
        '''</summary>
        Public ReadOnly Property PrecisionModeBoxName() As String
            Get
                Return ResourceManager.GetString("PrecisionModeBoxName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Precision Mode.
        '''</summary>
        Public ReadOnly Property PrecisionModeStrip() As String
            Get
                Return ResourceManager.GetString("PrecisionModeStrip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enables Precision Camera Mode, which lets you
        '''control the angle of the camera from Mario&apos;s first-person
        '''view and lock it wherever you want, and then readjust the camera at will..
        '''</summary>
        Public ReadOnly Property PrecisionModeTooltip() As String
            Get
                Return ResourceManager.GetString("PrecisionModeTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Precision Mode is disabled.
        '''Enable it in Settings -&gt; Precision Mode or use CTRL+P.
        '''</summary>
        Public ReadOnly Property PrecisionStatusDisabled() As String
            Get
                Return ResourceManager.GetString("PrecisionStatusDisabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Camera locked. Press the button below or use CTRL+SHIFT+P to re-adjust camera angle.
        '''To disable precision mode, uncheck Settings -&gt; Precision Mode or use CTRL+P.
        '''</summary>
        Public ReadOnly Property PrecisionStatusFinish() As String
            Get
                Return ResourceManager.GetString("PrecisionStatusFinish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Precision mode is disabled. Reason: Project64 isn&apos;t open..
        '''</summary>
        Public ReadOnly Property PrecisionStatusNoEmu() As String
            Get
                Return ResourceManager.GetString("PrecisionStatusNoEmu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Randomizer: X.
        '''</summary>
        Public ReadOnly Property RandomX() As String
            Get
                Return ResourceManager.GetString("RandomX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Randomizer: Y.
        '''</summary>
        Public ReadOnly Property RandomY() As String
            Get
                Return ResourceManager.GetString("RandomY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Randomizer: Z.
        '''</summary>
        Public ReadOnly Property RandomZ() As String
            Get
                Return ResourceManager.GetString("RandomZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remember previous animation swaps.
        '''</summary>
        Public ReadOnly Property RememberPrevSwaps() As String
            Get
                Return ResourceManager.GetString("RememberPrevSwaps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to When you select a new animation to be overwritten, any previous animations
        '''will remain swapped until you manually change or reset them..
        '''</summary>
        Public ReadOnly Property RememberPrevSwapsTooltip() As String
            Get
                Return ResourceManager.GetString("RememberPrevSwapsTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reset all animations to default (Malfunctioning).
        '''</summary>
        Public ReadOnly Property ResetAllSwaps() As String
            Get
                Return ResourceManager.GetString("ResetAllSwaps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This resets all animations to their original sequences.
        '''However, it currently does not work as intended, so
        '''I have disabled it until I determine how to fix it..
        '''</summary>
        Public ReadOnly Property ResetAllSwapsTooltip() As String
            Get
                Return ResourceManager.GetString("ResetAllSwapsTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Right.
        '''</summary>
        Public ReadOnly Property Right() As String
            Get
                Return ResourceManager.GetString("Right", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scanning for base address....
        '''</summary>
        Public ReadOnly Property SearchingForBaseAddress() As String
            Get
                Return ResourceManager.GetString("SearchingForBaseAddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Settings.
        '''</summary>
        Public ReadOnly Property SettingsMenu() As String
            Get
                Return ResourceManager.GetString("SettingsMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Small Extras.
        '''</summary>
        Public ReadOnly Property SmolExtrasName() As String
            Get
                Return ResourceManager.GetString("SmolExtrasName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove HUD.
        '''</summary>
        Public ReadOnly Property SmolExtrasNOHUD() As String
            Get
                Return ResourceManager.GetString("SmolExtrasNOHUD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Soft-Freeze Camera.
        '''</summary>
        Public ReadOnly Property SoftFreezeCamera() As String
            Get
                Return ResourceManager.GetString("SoftFreezeCamera", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Soft-Unfreeze Camera.
        '''</summary>
        Public ReadOnly Property SoftUnfreezeCamera() As String
            Get
                Return ResourceManager.GetString("SoftUnfreezeCamera", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tools.
        '''</summary>
        Public ReadOnly Property ToolsMenu() As String
            Get
                Return ResourceManager.GetString("ToolsMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Undo previous animation swaps.
        '''</summary>
        Public ReadOnly Property UndoAllPrevSwaps() As String
            Get
                Return ResourceManager.GetString("UndoAllPrevSwaps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to When you select a new animation to be overwritten, the previous one
        '''will be returned to its default animation..
        '''</summary>
        Public ReadOnly Property UndoAllPrevSwapsTooltip() As String
            Get
                Return ResourceManager.GetString("UndoAllPrevSwapsTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unfreeze Camera.
        '''</summary>
        Public ReadOnly Property UnfreezeCamera() As String
            Get
                Return ResourceManager.GetString("UnfreezeCamera", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
